version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build'
          command: 'yarn build:storybook'
      - run:
          name: 'Test'
          command: 'yarn test'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: 'yarn deploy:firebase'
      - run:
          name: Authenticate with registry
          command: npm login --registry=https://npm.pkg.github.com --scope=@tenjojeremy
      - run:
          name: Publish package to Github Packages
          command: yarn publish:minor
