version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint files
          command: yarn lint:check

      - run:
          name: Build Storybook
          command: yarn build:storybook

      - run:
          name: Deploy to Firebase
          command: yarn deploy:firebase
