version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build'
          command: 'yarn build:storybook'
      - run:
          name: 'Test'
          command: 'yarn test'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: 'yarn deploy:firebase'
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=fc3219040f6ec91884e05dbb8188554dc80e7a7a" > .npmrc
      - run:
          name: list
          command: dir
      - run:
          name: Publish package to Github registry
          command: npm publish
