version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=fc3219040f6ec91884e05dbb8188554dc80e7a7a" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
