import { string, func, array, bool } from 'prop-types'

export const defaultProps = {
  Wrapper: null,
  Input: null,
  IconLeftCon: null,
  IconRightCon: null,
  InputCon: null,
  CloseIconCon: null,
  type: 'text',
  name: 'UNAMEDtextField',
  validation: [],
  font: 'primary',
  color: 'white',
  foregroundColor: 'primary',
  backgroundColor: 'white',
  textColor: 'black',
  round: null,
  iconLeft: null,
  iconRight: null,
  placeholder: null,
  width: 'fit-content',
  label: null,
  autocomplete: 'off',
  initialInput: '',
  clearOnSubmit: null,
  dataCy: null,
  setInSessionStorage: null,
  onFocus: () => null,
  onBlur: () => null,
  onLeftIconClick: () => null,
  onRightIconClick: () => null,
  onInput: () => null,
}

export const propTypes = {
  onFocus: func,
  type: string,
  name: string,
  validation: array,
  font: string,
  color: string,
  foregroundColor: string,
  backgroundColor: string,
  textColor: string,
  round: bool,
  iconLeft: string,
  iconRight: string,
  placeholder: string,
  onBlur: func,
  onInput: func,
  width: string,
  label: string,
  onLeftIconClick: func,
  onRightIconClick: func,
  autocomplete: string,
  initialInput: string,
  clearOnSubmit: bool,
  setInSessionStorage: bool,
  dataCy: string,
}
