name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo "//packagecloud.io/armando/node-test-package/npm/:_authToken=${{secrets.gpnToken}}" > ~/repo/.npmrc
      - run: yarn    
      - run: yarn lint:check
      - run: yarn cy:run-ci
      - run: yarn build:storybook

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@tenjojeremy'
      - run: npm publish --minor
        env:
          NODE_AUTH_TOKEN: ${{secrets.gpnToken}}
